# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LYCore' do
  use_frameworks!

  # Pods for LYCore
  pod 'LYCategory'
  pod 'AFNetworking'
  pod 'FCFileManager'

end
